<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Remcoposer64.Core\Remcoposer64.Core.csproj" />
    <ProjectReference Include="..\Remcoposer64.StepEditorPanel\Remcoposer64.StepEditorPanel.csproj" />
  </ItemGroup>

</Project>